name: Integration Tests on Databricks Billing

on:
  push:
    branches:
      - feature/add-ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd integration_tests
        pip install -r requirements.txt
        dbt deps

    - name: Integration Test - Snowflake
      run: cd integration_tests && dbt build --target snowflake
