name: Integration Tests, CI

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main   

env:
  DBT_DEFAULT_TARGET: databricks
  DBT_PROFILES_DIR: ${{ github.workspace }}/integration_tests
  DBT_PROJECT_DIR: ${{ github.workspace }}/integration_tests

  DATABRICKS_TEST_HOST: ${{ secrets.DATABRICKS_TEST_HOST }}
  DATABRICKS_TEST_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
  DATABRICKS_TEST_TOKEN: ${{ secrets.DATABRICKS_TEST_TOKEN }}
  DATABRICKS_TEST_CATALOG: ${{ vars.DATABRICKS_TEST_CATALOG }}
  DATABRICKS_TEST_SCHEMA: dbt_ci_${{ github.ref_name }}_${{ github.run_number }}
  CLEANED_BRANCH: "${{ github.ref_name }}"

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd integration_tests/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        dbt deps

    - name: Integration Test - Databricks Billing
      run: |
        dbt seed 

        dbt run-operation warehouses

        dbt run-operation clusters

        dbt test -s source:* 

        dbt build --exclude-resource-type seed 

        dbt run-operation drop_schemas_dev --args '{pattern: dbt_ci_"${GITHUB_REF_NAME}"_*}'